name: build.yml
on:
  workflow_dispatch:
  push:
    tags: [ v* ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Linux setup
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            --no-install-recommends \
            xvfb \
            libnss3 \
            libasound2 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libgdk-pixbuf2.0-dev \
            libgtk-3-0 \
            libgbm1
          sudo add-apt-repository -y ppa:alexlarsson/flatpak

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '24.15.x'
          cache: 'npm'

      - name: Fix python version
        uses: actions/setup-python@v7
        with:
          python-version: '3.12.3'

      - name: Setup dependencies
        run: npm install --production=false

      - name: package artifacts
        run: NODE_ENV=development npm run package

      - name: Build and publish artifacts
        run: NODE_ENV=development npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}