name: build.yml
on:
  push:
    tags: [ v* ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '24.15.x'

      - name: Setup dependencies
        run: npm install

      - name: Build and publish artifacts
        run: npm run publish